"use client";
import { useEffect, useState, type ReactNode, type ButtonHTMLAttributes } from "react";
import Link from "next/link";
export function SourceIcon({id,size=20}:{id:number;size?:number}){return <img src={`/assets/icons/icon-${id}.svg`} width={size} height={size} alt="" aria-hidden="true"/>}
export function ActionButton({secondary=false,children,className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{secondary?:boolean}){return <button className={`cs-button ${secondary?'secondary':''} ${className}`} {...props}>{children}</button>}
export function Panel({children,title,className=''}:{children:ReactNode;title?:ReactNode;className?:string}){return <section className={`cs-panel ${className}`}>{title&&<h2 className="cs-panel-title">{title}</h2>}{children}</section>}
export function PageHeading({title,children}:{title:string;children?:ReactNode}){return <div className="cs-page-heading"><h1>{title}</h1>{children}</div>}
export function EmptyState({text='데이터가 없습니다',border=false}:{text?:string;border?:boolean}){return <div className={`cs-empty ${border?'bordered':''}`}><SourceIcon id={38} size={120}/><p>{text}</p></div>}
export function DataTable({columns,rows=[],empty='데이터가 없습니다',initialSize=10}:{columns:string[];rows:ReactNode[][];empty?:string;initialSize?:number}){const [size,setSize]=useState(initialSize),[page,setPage]=useState(1);const pages=Math.max(1,Math.ceil(rows.length/size));const current=Math.min(page,pages);return <><div className="cs-table-wrap"><table className="cs-table"><thead><tr>{columns.map((x,i)=><th key={i}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.slice((current-1)*size,current*size).map((r,i)=><tr key={i}>{r.map((c,k)=><td key={k}>{c}</td>)}</tr>):<tr><td colSpan={columns.length}><EmptyState text={empty}/></td></tr>}</tbody></table></div><div className="cs-pagination"><select aria-label="페이지당 행 수" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}>{[5,10,20,50].map(n=><option key={n}>{n}</option>)}</select><div><button disabled={current===1} onClick={()=>setPage(current-1)} aria-label="이전 페이지">‹</button><button className="active">{current}</button><button disabled={current>=pages} onClick={()=>setPage(current+1)} aria-label="다음 페이지">›</button></div></div></>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler)},[onClose]);return <div className="cs-backdrop" onClick={onClose}><section className="cs-modal" role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><header><h2>{title}</h2><button aria-label="닫기" onClick={onClose}>×</button></header><div className="cs-modal-body">{children}</div></section></div>}
export function LicenseGate({enterprise=false}:{enterprise?:boolean}){return <div className="cs-gate"><h1>접근할 수 없습니다.</h1><p>{enterprise?'해당 라이선스에 제공되지 않는 기능입니다.':'유료 라이선스에 제공되는 기능입니다.'}<br/>{enterprise?'엔터프라이즈 라이선스 구독 후 사용하실 수 있습니다.':'라이선스 구독 후 사용하실 수 있습니다.'}</p><Link className="cs-button" href="/pay/membership/detail">라이선스 알아보기</Link></div>}
