"use client";
import { isValidElement, useMemo, useRef, useState, type ReactNode, type ButtonHTMLAttributes } from "react";
import Link from "next/link";
import { useDialogFocus } from "./ux/focus";
export function SourceIcon({id,size=20}:{id:number;size?:number}){return <img src={`/assets/icons/icon-${id}.svg`} width={size} height={size} alt="" aria-hidden="true"/>}
export function ActionButton({secondary=false,children,className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{secondary?:boolean}){return <button className={`cs-button ${secondary?'secondary':''} ${className}`} {...props}>{children}</button>}
export function Panel({children,title,className=''}:{children:ReactNode;title?:ReactNode;className?:string}){return <section className={`cs-panel ${className}`}>{title&&<h2 className="cs-panel-title">{title}</h2>}{children}</section>}
export function PageHeading({title,children}:{title:string;children?:ReactNode}){return <div className="cs-page-heading"><h1>{title}</h1>{children}</div>}
export function EmptyState({text='데이터가 없습니다',border=false}:{text?:string;border?:boolean}){return <div className={`cs-empty ${border?'bordered':''}`}><SourceIcon id={38} size={120}/><p>{text}</p></div>}
function cellText(node:ReactNode):string{if(node==null||typeof node==='boolean')return '';if(typeof node==='string'||typeof node==='number')return String(node);if(Array.isArray(node))return node.map(cellText).join('');if(isValidElement(node))return cellText((node.props as {children?:ReactNode}).children);return ''}
const collator=new Intl.Collator('ko',{numeric:true,sensitivity:'base'});
export function DataTable({columns,rows=[],empty='데이터가 없습니다',initialSize=10,sortable=true}:{columns:string[];rows:ReactNode[][];empty?:string;initialSize?:number;sortable?:boolean}){const [size,setSize]=useState(initialSize),[page,setPage]=useState(1),[sort,setSort]=useState<{col:number;dir:1|-1}|null>(null);const sorted=useMemo(()=>sort?[...rows].sort((a,b)=>sort.dir*collator.compare(cellText(a[sort.col]),cellText(b[sort.col]))):rows,[rows,sort]);const pages=Math.max(1,Math.ceil(sorted.length/size));const current=Math.min(page,pages);return <><div className="cs-table-wrap"><table className="cs-table"><thead><tr>{columns.map((x,i)=><th key={i} aria-sort={sort?.col===i?(sort.dir>0?'ascending':'descending'):undefined}>{sortable?<button type="button" className="ux-sort" aria-label={`${x} 열 ${sort?.col===i?(sort.dir>0?'오름차순 정렬됨':'내림차순 정렬됨'):'정렬'}`} onClick={()=>{setPage(1);setSort(s=>s?.col===i?{col:i,dir:(s.dir>0?-1:1)as 1|-1}:{col:i,dir:1})}}>{x}<span aria-hidden="true">{sort?.col===i?(sort.dir>0?' ↑':' ↓'):' ↕'}</span></button>:x}</th>)}</tr></thead><tbody>{sorted.length?sorted.slice((current-1)*size,current*size).map((r,i)=><tr key={i}>{r.map((c,k)=><td key={k}>{c}</td>)}</tr>):<tr><td colSpan={columns.length}><EmptyState text={empty}/></td></tr>}</tbody></table></div><div className="cs-pagination"><select aria-label="페이지당 행 수" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}>{[5,10,20,50].map(n=><option key={n}>{n}</option>)}</select><div><button disabled={current===1} onClick={()=>setPage(current-1)} aria-label="이전 페이지">‹</button><button className="active">{current}</button><button disabled={current>=pages} onClick={()=>setPage(current+1)} aria-label="다음 페이지">›</button></div></div></>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLElement>(null);useDialogFocus(ref,onClose);return <div className="cs-backdrop" onClick={onClose}><section ref={ref} className="cs-modal" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} onClick={e=>e.stopPropagation()}><header><h2>{title}</h2><button type="button" aria-label="닫기" data-dialog-close onClick={onClose}>×</button></header><div className="cs-modal-body">{children}</div></section></div>}
export function LicenseGate({enterprise=false}:{enterprise?:boolean}){return <div className="cs-gate"><h1>접근할 수 없습니다.</h1><p>{enterprise?'해당 라이선스에 제공되지 않는 기능입니다.':'유료 라이선스에 제공되는 기능입니다.'}<br/>{enterprise?'엔터프라이즈 라이선스 구독 후 사용하실 수 있습니다.':'라이선스 구독 후 사용하실 수 있습니다.'}</p><Link className="cs-button" href="/pay/membership/detail">라이선스 알아보기</Link></div>}
