import type { QuestionMaterial } from "./question-materials";
import { z } from "zod";
import type { FileInfo } from "./files";
import type { Answers, MatrixRows, OptionDefinition } from "./questions";
import type { RichDocumentV1 } from "./rich-content";
const email = z.string().trim().toLowerCase().max(254).pipe(z.email());
const questionIds = z.array(z.uuid()).min(1, "공유할 항목을 선택해주세요.").max(100)
  .refine(values => new Set(values).size === values.length, "공유 항목이 중복되었습니다.");
const expiry = z.iso.datetime({ offset: true });
export const shareCreateInput = z.object({ formId: z.uuid(), formVersionId: z.uuid(), email, questionIds, expiresAt: expiry, shareFormBody: z.boolean().default(false) }).strict();
export const shareUpdateInput = z.object({ version: z.number().int().positive(), email, questionIds, expiresAt: expiry, shareFormBody: z.boolean().default(false) }).strict();
export const shareVersionInput = z.object({ version: z.number().int().positive() }).strict();
export const challengeInput = z.object({ formCode: z.uuid(), invitationCode: z.string().regex(/^[A-Za-z0-9_-]{43}$/), email, consent: z.literal(true) }).strict();
export const challengeIdInput = z.string().regex(/^[A-Za-z0-9_-]{43}$/);
export const verificationInput = z.object({ code: z.string().regex(/^\d{6}$/) }).strict();
const pagination = { page: z.coerce.number().int().min(1).max(100000).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(20) };
export const shareListQuery = z.object({ ...pagination, formId: z.uuid(), status: z.enum(["all", "active", "expired", "revoked"]).default("all"), search: z.string().trim().toLowerCase().max(254).default("") }).strict();
export const sharingPageQuery = z.object(pagination).strict();
export const shareOptionsQuery = z.object({ formId: z.uuid() }).strict();
export const sharingEmptyQuery = z.object({}).strict();
export const shareCreationResult = z.object({ id: z.uuid(), formId: z.uuid(), formVersionId: z.uuid(), version: z.number().int().positive(), status: z.enum(["active", "expired", "revoked"]) });
export type ShareInput = z.input<typeof shareCreateInput>;
export type ShareUpdate = z.input<typeof shareUpdateInput>;
export type SharedQuestion = { questionImageKey?: string; materialList?: QuestionMaterial[]; id: string; label: string; type: string; rows?: MatrixRows; optionDefinitions?: OptionDefinition[] };
export type SharePermissions = { canCreate: boolean; canSelectFiles: boolean; reason: string | null };
export type ShareActions = { edit: boolean; resend: boolean; revoke: boolean };
export type ShareRecord = {
  id: string; formId: string; formVersionId: string; formTitle: string; formNumber: number; email: string;
  questionIds: string[]; questions: SharedQuestion[]; expiresAt: string; status: "active" | "expired" | "revoked";
  shareFormBody: boolean;
  version: number; createdAt: string;
  actions: ShareActions;
};
export type SharePage = { items: ShareRecord[]; total: number; page: number; pageSize: number; permissions: SharePermissions };
export type ShareOptions = { formCode: string; permissions: SharePermissions; versions: { id: string; number: number; title: string; questions: (SharedQuestion & { selectable: boolean })[] }[] };
export type SharedPresentation = { body: string; bodyRich?: RichDocumentV1 };
export type SharedPagePresentation = SharedPresentation & { id: string; title: string };
export type ViewerInfo = { formTitle: string; formNumber: number; questions: SharedQuestion[]; formBody?: SharedPresentation;
  pages: SharedPagePresentation[]; expiresAt: string; grantExpiresAt: string };
export type SharedSubmission = { id: string; submittedAt: string; values: Answers; attachments: FileInfo[] };
export type SharedPage = { items: SharedSubmission[]; total: number; page: number; pageSize: number; viewer: ViewerInfo };
export type ShareEvent = { id: string; action: string; createdAt: string; detail: { changedFields?: string[]; submissionId?: string; fileId?: string } };
