"use client";
import {ActivityReviews} from "./ActivityReviews";
import {SecurityOverview} from "./SecurityOverview";
import {MfaPolicy} from "./MfaPolicy";
import { IpAccess } from "./IpAccess";
import {ApprovalLog} from "../forms/Approvals";
import {LiveMembers} from "./members";
import {DestructionPages} from "./destruction";
import {AuditLogs,hasAuditLog} from "./AuditLogs";
import {LiveAccountClosure as DeleteProfile} from "./AccountClosure";
import Link from 'next/link';import {LiveCompany,LiveServices,LiveServiceEditor,LiveProfile} from './live';import {Logs,hasLog} from './logs';import {Policy} from './policy';import {ConsentDisplay} from "./ConsentDisplay";import {SubprocessorMail} from "./SubprocessorMail";import './management.css';
const enterprise=['/set/company/policy','/log/authority','/log/destruction_certificate','/log/form-approval','/log/destruction-schedule','/log/month-monitoring','/log/access-history','/security/compliance','/security/sso','/security/sso/setting','/security/ip','/security/ip/setting'];const paid=['/log/mail','/log/member','/log/external-viewer'];
export function matchManagement(path:string){return /^\/(set|log|security|my-page)(\/|$)/.test(path)}
function Gate({enterprise=false}:{enterprise?:boolean}){return <div className="mg-gate-wrap"><div className="mg-gate"><h2>접근할 수 없습니다.</h2><div className="mg-gate-note"><span className="mg-gate-icon">!</span><div><strong>{enterprise?'해당 라이선스에 제공되지 않는 기능입니다.':'유료 라이선스에 제공되는 기능입니다.'}</strong><p>{enterprise?'엔터프라이즈 라이선스 구독 후 사용하실 수 있습니다.':'라이선스 구독 후 사용하실 수 있습니다.'}</p></div></div></div></div>}
export function ManagementPages({path}:{path:string}){if(path==='/my-page/info-activity-log')return <ActivityReviews/>;if(path==='/security'||path==='/security/compliance')return <SecurityOverview/>;if(path==='/security/two-factor'||path==='/security/two-factor/setting')return <MfaPolicy settings={path.endsWith('/setting')}/>;if(path==='/security/ip'||path==='/security/ip/setting')return <IpAccess settings={path.endsWith('/setting')}/>;if(path==='/set/member'||path==='/set/authority')return <LiveMembers authority={path==='/set/authority'}/>;if(path==='/set/company/policy')return <Policy/>;if(path==='/log/form-approval')return <ApprovalLog/>;if(path==='/log/destruction-schedule')return <DestructionPages/>;if(path==='/log/destruction_certificate')return <DestructionPages certificates/>;if(hasAuditLog(path))return <AuditLogs key={path} path={path}/>;if(enterprise.includes(path))return <Gate enterprise/>;if(paid.includes(path))return <Gate/>;if(hasLog(path))return <Logs key={path} path={path}/>;switch(path){case '/set/company':return <LiveCompany/>;case '/set/company/edit':return <LiveCompany edit/>;case '/set/service':return <LiveServices/>;case '/set/service/modification':return <LiveServiceEditor/>;case '/set/company/policy/setting':return <Policy/>;case '/set/service/consent':return <ConsentDisplay/>;case '/set/service/consigment/mail':return <SubprocessorMail/>;case '/my-page/info':return <LiveProfile/>;case '/my-page/info/edit':return <LiveProfile edit/>;case '/my-page/delete':return <DeleteProfile/>;case '/my-page':return null;case '/security':return <div className="mg-unavailable">원본 경로에서 화면이 표시되지 않았습니다. <Link href="/dashboard">대시보드</Link></div>;case '/set/authority':case '/security/two-factor':case '/security/two-factor/setting':return <div className="mg-unavailable">원본에서 대시보드로 이동하는 경로입니다. <Link className="cs-button" href="/dashboard">대시보드로 이동</Link></div>;default:return <p className="mg-unavailable">이 경로의 원본 화면을 확인하지 못했습니다.</p>}}
