import { db } from "../src/server/db";
import { decrypt } from "../src/server/crypto";
import { readFile } from "node:fs/promises";
import { env } from "../src/server/env";
const base = new URL(env.BETTER_AUTH_URL).origin;
const pw = JSON.parse(await readFile(".local/catchsecu_dev-accounts.json","utf8"));
const res = await fetch(base+"/api/v1/auth/sign-in/email",{method:"POST",redirect:"manual",headers:{origin:base,"content-type":"application/json"},body:JSON.stringify({email:"owner@catchsecu.local.test",password:pw["owner@catchsecu.local.test"]})});
const cookie = res.headers.getSetCookie().map(v=>v.split(";")[0]).join("; ");
const pub = await db.publication.findFirst({where:{tenantId:"10000000-0000-4000-8000-000000000001",status:"active"},include:{formVersion:{select:{id:true,number:true}}}});
const token = decrypt(pub!.tokenCipher);
const out: Record<string,unknown> = {};
out.publicFormPage = (await fetch(`${base}/projects/${token}/form`,{redirect:"manual"})).status;
out.publicApi = (await fetch(`${base}/api/v1/public/forms/${token}`)).status;
out.legacyAlias = (await fetch(`${base}/project/${token}/form`,{redirect:"manual"})).status;
out.testAlias = (await fetch(`${base}/test-projects/${token}/form`,{redirect:"manual"})).status;
const p1 = await fetch(`${base}/api/v1/forms/${pub!.formId}/versions/${pub!.formVersionId}`,{method:"PATCH",headers:{origin:base,"content-type":"application/json",cookie,"Idempotency-Key":"qa-v-"+Date.now()},body:JSON.stringify({version:pub!.formVersion.number,title:"직접수정시도"})});
out.patchPublished = {s:p1.status, code:(await p1.json()).error?.code};
console.log(JSON.stringify(out));
await fetch(base+"/api/v1/auth/sign-out",{method:"POST",headers:{origin:base,cookie}});
await db.$disconnect();
