import assert from "node:assert/strict";
import { readFile, writeFile, access } from "node:fs/promises";
import { join, resolve } from "node:path";
import { createHash } from "node:crypto";
import { auth } from "../src/server/auth";
import { db } from "../src/server/db";
import { env } from "../src/server/env";
import { GET as fileGet } from "../src/app/api/v1/files/[...segments]/route";
import { GET as viewerGet } from "../src/app/api/v1/viewer/[...segments]/route";
import { DELETE as revokeShare } from "../src/app/api/v1/share-grants/[...segments]/route";
import { POST as requestDestruction } from "../src/app/api/v1/submissions/[...segments]/route";
import { POST as decideDestruction } from "../src/app/api/v1/destruction-requests/[...segments]/route";
import { runOneDestruction } from "../src/server/destruction-worker";
const url = new URL(env.DATABASE_URL);
assert.match(url.pathname, /^\/catchsecu_mock_restore_[a-f0-9]{8}$/);
assert.ok(["localhost", "127.0.0.1"].includes(url.hostname));
assert.equal(resolve(env.PRIVATE_STORAGE_DIR), resolve(".local/mock-restores", url.pathname.slice(1), "storage"));
const fixture = JSON.parse(await readFile(".local/mock-page-fixtures.json", "utf8"));
const origin = new URL(env.BETTER_AUTH_URL).origin;
assert.equal(origin, fixture.origin);
const checks: { name: string; status: number }[] = [];
try {
  const login = await auth.handler(new Request(origin + "/api/v1/auth/sign-in/email", { method: "POST", headers: { origin, "content-type": "application/json" }, body: JSON.stringify({ email: fixture.email, password: fixture.password }) }));
  assert.equal(login.status, 200); checks.push({ name: "restored owner login", status: 200 });
  const cookie = login.headers.getSetCookie().map(v => v.split(";")[0]).join("; ");
  const [, , submissionId, questionId, fileId] = fixture.routes["/file-view/:customerId/:questionId/:fileId"].split("/");
  const query = `?submissionId=${submissionId}&questionId=${questionId}`;
  const request = (path: string, c: string) => new Request(origin + "/api/v1" + path, { headers: { cookie: c } });
  const row = await db.fileObject.findUniqueOrThrow({ where: { id: fileId } });
  const download = await fileGet(request(`/files/${fileId}/download${query}`, cookie));
  assert.equal(download.status, 200);
  assert.equal(createHash("sha256").update(Buffer.from(await download.arrayBuffer())).digest("hex"), row.sha256);
  checks.push({ name: "restored encrypted file downloaded with matching plaintext hash", status: 200 });
  const denied = await fileGet(request(`/files/${fileId}/download${query}`, ""));
  assert.equal(denied.status, 401); checks.push({ name: "restored file denies anonymous", status: 401 });
  const viewerCookie = fixture.viewer.cookies.map((c: { name: string; value: string }) => `${c.name}=${c.value}`).join("; ");
  const shared = await viewerGet(request(`/viewer/files/${fileId}/download${query}`, viewerCookie));
  assert.equal(shared.status, 200); assert.equal(createHash("sha256").update(Buffer.from(await shared.arrayBuffer())).digest("hex"), row.sha256);
  checks.push({ name: "restored scoped viewer file byte hash", status: 200 });
  const grant = await db.shareGrant.findFirstOrThrow({ where: { tenantId: fixture.companyId, formId: fixture.formId, revokedAt: null } });
  const revoke = await revokeShare(new Request(origin + "/api/v1/share-grants/" + grant.id, { method: "DELETE", headers: { origin, cookie, "if-match": String(grant.version) } }));
  assert.equal(revoke.status, 200);
  assert.equal((await viewerGet(request(`/viewer/files/${fileId}/download${query}`, viewerCookie))).status, 401);
  checks.push({ name: "restored share revocation immediately blocks old cookie", status: 401 });
  const submission = await db.submission.findUniqueOrThrow({ where: { id: submissionId } });
  const post = (path: string, body: unknown) => new Request(origin + "/api/v1" + path, { method: "POST", headers: { origin, cookie, "content-type": "application/json" }, body: JSON.stringify(body) });
  const requested = await requestDestruction(post(`/submissions/${submissionId}/destruction-request`, { version: submission.version, reason: "Mock 복원 재파기" }));
  assert.equal(requested.status, 200);
  const destructionId = (await requested.json()).destructionId;
  const destruction = await db.destructionRequest.findUniqueOrThrow({ where: { id: destructionId } });
  const approved = await decideDestruction(post(`/destruction-requests/${destructionId}/approve`, { version: destruction.version, reason: "Mock 복원 재파기 승인" }));
  assert.equal(approved.status, 200);
  assert.equal(await runOneDestruction("mock-restore-proof", new Date(), { tenantId: fixture.companyId, requestId: destructionId }), true);
  assert.equal((await db.submission.findUniqueOrThrow({ where: { id: submissionId } })).status, "destroyed");
  assert.equal(await db.answer.count({ where: { submissionId } }), 0);
  assert.equal(await db.destructionCertificate.count({ where: { submissionId } }), 1);
  await assert.rejects(access(join(env.PRIVATE_STORAGE_DIR, "objects", row.storageKey + ".enc")), { code: "ENOENT" });
  const removed = await fileGet(request(`/files/${fileId}/download${query}`, cookie));
  assert.ok([404, 410].includes(removed.status));
  checks.push({ name: "restored submission re-destroyed; answers and object erased, certificate retained", status: removed.status });
  await writeFile(process.env.MOCK_RESTORE_API_REPORT!, JSON.stringify({ checkedAt: new Date().toISOString(), result: "passed", checks }, null, 2) + "\n");
  console.log(JSON.stringify({ result: "passed", checks: checks.length }));
} catch (error) {
  await writeFile(process.env.MOCK_RESTORE_API_REPORT!, JSON.stringify({ checkedAt: new Date().toISOString(), result: "failed", checks }, null, 2) + "\n");
  throw error;
} finally { await db.$disconnect(); }
